### ISSUE TITLE
[feature] create class model with name ImageRecogModel

### ISSUE THREAD

**Issue by nunenuh** [lombokai/onepiece-classifier#3]
- create class model with inheritance from class nn.Module from torch.nn
- create function as a wrapper to create the class and return the output function with object of class ImageRecogModel
- create test package models and file test_image_recog_models and run with pytest

**Comment by AnnurAfgoni** [comment]
Has been done by creating ImageRecogModel class, instantiate it into ImageRecog function, and create a test file and the test is using pytest.

**Comment by nunenuh** [comment]
okay, i've check your code, at least it work and looks good
